### PR TITLE
Update my_home_page.dart

### PR DESCRIPTION
**Pull request by skfareeduddin**
This is my proposed solution to your issue.

### CODE REVIEW

**Comment by fullstackctp** [comment]
@skfareeduddin 
Could you please link the issue with PR.

**Comment by skfareeduddin** [comment]
Sure! @fullstackctp this was the issue:- [Issue Link](https://github.com/oxyfalcon/firebase_todo/issues/7)

**Comment by skfareeduddin** [comment]
Sure! @fullstackctp this was the issue:- [Issue Link](https://github.com/oxyfalcon/firebase_todo/issues/7)

**Comment by oxyfalcon** [comment]
@skfareeduddin Could you please fix the linting issue.

**Comment by skfareeduddin** [comment]
sure!

**Comment by skfareeduddin** [comment]
done. solved the linting issue. @oxyfalcon

**Review by oxyfalcon — APPROVED** [review]
LGTM!

**Pull request merged**
